version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: puzzle
      MYSQL_USER: puzzle
      MYSQL_PASSWORD: puzzle
    volumes:
      - ~/tpmhdata/mysql-data:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"

  redis:
    image: redis:3.2.10
    restart: always
    volumes:
      - ~/tpmhdata/redis-data:/data
    ports:
      - "127.0.0.1:6379:6379"

  puzzle-dev:
    depends_on:
      - db
      - redis
    build: .
    ports:
      - "127.0.0.1:8000:80"
    restart: always
    environment:
      HUNT_MYSQL_HOST: db
      HUNT_MYSQL_PORT: 3306
      HUNT_MYSQL_USER: puzzle
      HUNT_MYSQL_PASSWORD: puzzle
      HUNT_MYSQL_DB: puzzle
      HUNT_SESSION_SECRET: sosecret
      HUNT_REDIS_URL: 'redis://redis:6379'
      HUNT_PORT: 80
      HUNT_CORS_ORIGIN: '*'
      HUNT_AUTH_ALLOW_DEV: 'true'
      HUNT_AUTH_JWT_SECRET: 'devsecret'
      HUNT_CANONICAL_PUZZLE_ID: 'TBD'
      HUNT_AUTH_ADMIN_PW: 'devpassword'
      TPMH_DEVMODE: 'false'
      TPMH_ADMIN_KEY: 'asdf'
      TPMH_JWT_CHALLENGE_SECRET: 'ad6768b93025f8ba509e224f5dded6387c2b12335a4990679cd80619548d7b5c'
      SIMULATION_SERVICE_ADDRESS: 'http://puzzle-sim'
      # Or, to talk to a local instance:
      # SIMULATION_SERVICE_ADDRESS: 'http://docker.for.mac.localhost:8080'
    command: "/wait-for-it.sh db:3306 -- /wait-for-it.sh redis:6379 -- node /app/src/index.js"
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh

  puzzle-sim:
    depends_on:
      - db
      - redis
    build: ./go/src/hunt/tpmhsim
    restart: always
    environment:
      HUNT_MYSQL_HOST: db
      HUNT_MYSQL_PORT: 3306
      HUNT_MYSQL_USER: puzzle
      HUNT_MYSQL_PASSWORD: puzzle
      HUNT_MYSQL_DB: puzzle
      HUNT_REDIS_URL: 'redis://redis:6379'
      HUNT_PORT: 80
      TPMHSIM_DEBUG: 'true'
    command: "/wait-for-it.sh db:3306 -- /wait-for-it.sh redis:6379 -- /tpmhsim"
    volumes:
      - ./wait-for-it-alpine.sh:/wait-for-it.sh

  # puzzle-prod:
  #   depends_on:
  #     - db
  #     - redis
  #   build: .
  #   ports:
  #     - "8000:80"
  #   restart: always
  #   environment:
  #     HUNT_MYSQL_HOST: db
  #     HUNT_MYSQL_PORT: 3306
  #     HUNT_MYSQL_USER: puzzle
  #     HUNT_MYSQL_PASSWORD: puzzle
  #     HUNT_MYSQL_DB: puzzle
  #     HUNT_SESSION_SECRET: sosecret
  #     HUNT_REDIS_URL: 'redis://redis:6379'
  #     HUNT_PORT: 80
  #     HUNT_CORS_ORIGIN: '*'
  #   command: "/wait-for-it.sh db:3306 -- /wait-for-it.sh redis:6379 -- node /app/src/index.js"
  #   volumes:
  #     - ./wait-for-it.sh:/wait-for-it.sh

